### ISSUE TITLE
Has anyone implimented the "follow" feature of the Twitter's straeming API in conjuction with this script?

### ISSUE THREAD

**Issue by ahusmc** [gdelfresno/twitterstream-to-mongodb#6]
I'm looking to track a list of users and all references associated to those users, in the objects file, with this script. Has anyone expanded upon this script by adding the follow feature of the streaming API?

**Comment by edent** [comment]
So, here's a quick and dirty way to do this.  Change the line

     STREAM_URL = "https://stream.twitter.com/1/statuses/filter.json?track=%s"

to

     STREAM_URL = "https://stream.twitter.com/1/statuses/filter.json?follow=%s"

And create a text file with a list of user ids - one on each line - called `follow.txt`.

Then run your command as normal

    python twitterstreamtomongodb.py --oauth=oauth.json --server=localhost --port=27017 --database=TwitterStream --track=follow.txt

Like I say, quick and dirty :-)

**Comment by ahusmc** [comment]
Thanks so much for replying to this older message. I will incorporate your method into my collection model.

**Comment by gdelfresno** [comment]
I just added the option --follow to do just what you asked. Thanks for the suggestion.

**Comment by ahusmc** [comment]
Thanks for adding the --follow option. Your script helped me accomplish my undergrad thesis.
